"""add applications

Revision ID: 114aed42ff01
Revises: f8b80b870dc0
Create Date: 2016-06-23 00:02:25.589797

"""

# revision identifiers, used by Alembic.
revision = '114aed42ff01'
down_revision = 'f8b80b870dc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    ### end Alembic commands ###
