"""add applications

Revision ID: af26ec4ca8ed
Revises: f4f5d963ab4c
Create Date: 2016-06-23 00:54:34.968306

"""

# revision identifiers, used by Alembic.
revision = 'af26ec4ca8ed'
down_revision = 'f4f5d963ab4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_applications_timestamp'), 'applications', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_timestamp'), table_name='applications')
    op.drop_column('applications', 'timestamp')
    ### end Alembic commands ###
