"""add applications

Revision ID: f4f5d963ab4c
Revises: 114aed42ff01
Create Date: 2016-06-23 00:06:51.943104

"""

# revision identifiers, used by Alembic.
revision = 'f4f5d963ab4c'
down_revision = '114aed42ff01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_passed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_passed')
    ### end Alembic commands ###
