"""add people_amount

Revision ID: f8b80b870dc0
Revises: None
Create Date: 2016-06-22 16:34:03.867759

"""

# revision identifiers, used by Alembic.
revision = 'f8b80b870dc0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('people_amount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'people_amount')
    ### end Alembic commands ###
